[package]
name = "marktask"
version = "0.1.0"
edition = "2021"


[lib]
name = "marktask"
path = "src/lib.rs"

[[bin]]
name = "marktask"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "3.0"
regex = "1"